//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPABD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Databases
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public bool Wlaczona { get; set; }
        public string Owner { get; set; }
        public string Collation { get; set; }
        public string Type { get; set; }
        public Nullable<int> Status { get; set; }
        public int Id_DatabaseGroup { get; set; }
        public int Id_Servers { get; set; }
    
        public virtual DatabaseGroup DatabaseGroup { get; set; }
        public virtual Servers Servers { get; set; }
    }
}
