//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPABD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Latency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Latency()
        {
            this.BlokadyHistory = new HashSet<BlokadyHistory>();
            this.HostHistory = new HashSet<HostHistory>();
            this.LatencyHistory = new HashSet<LatencyHistory>();
            this.ProcesyHistory = new HashSet<ProcesyHistory>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Id_ServersS { get; set; }
        public int Id_ServersD { get; set; }
        public string Opis { get; set; }
        public string Typ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlokadyHistory> BlokadyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostHistory> HostHistory { get; set; }
        public virtual Servers Servers { get; set; }
        public virtual Servers Servers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LatencyHistory> LatencyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesyHistory> ProcesyHistory { get; set; }
    }
}
