//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPABD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginServers
    {
        public int Id { get; set; }
        public int Id_Login { get; set; }
        public int Id_Server { get; set; }
    
        public virtual Logins Logins { get; set; }
        public virtual Servers Servers { get; set; }
    }
}
