//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPABD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedury()
        {
            this.Files = new HashSet<Files>();
            this.ProceduryHistory = new HashSet<ProceduryHistory>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Body { get; set; }
        public System.DateTime Utworzona { get; set; }
        public Nullable<System.DateTime> Zmodyfikowana { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Id_Servers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Files> Files { get; set; }
        public virtual Servers Servers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProceduryHistory> ProceduryHistory { get; set; }
    }
}
