//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPABD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProceduryHistory
    {
        public int Id { get; set; }
        public int Id_Procedury { get; set; }
        public int Id_Servers { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Wynik { get; set; }
    
        public virtual Procedury Procedury { get; set; }
        public virtual Servers Servers { get; set; }
    }
}
